# https://taskfile.dev

version: '3'

vars:
  PROJECT: movies_api

tasks:

  default:
    cmds:
      - task: install

  install:
    desc: Install Python dependencies
    sources:
      - pyproject.toml
      - poetry.lock
    cmds:
      - poetry install

  test:
    desc: Run application test suite
    sources:
      - ./**/*.py
    deps:
      - format
    cmds:
      - poetry run pytest --cov={{.PROJECT}} --cov-report=term --cov-report=html --verbose

  format:
    desc: Format the codebase
    sources:
      - ./**/*.py
    cmds:
      - poetry run black .

  lint:
    desc: Lint the codebase for style issues
    sources:
      - ./**/*.py
    cmds:
      - poetry run black --check .
      - poetry run flake8 --show-source .

  dev:
    desc: Run the development server on localhost:{{.PORT}}
    cmds:
      - poetry run uvicorn main:app --reload --port {{.PORT}}
    vars:
      PORT: 8000

  docs:
    desc: Generate the OpenAPI documentation (run `task dev` first)
    dir: docs
    interactive: true
    cmds:
      - curl -sSL {{.SPEC_URL}} > openapi.json
      - poetry run python -m http.server {{.PORT}}
    vars:
      SPEC_URL: http://localhost:8000/openapi.json
      PORT: 8080
