# https://taskfile.dev

version: '3'

vars:
  PROJECT: movies_api

tasks:

  default:
    cmds:
      - task: install

  install:
    sources:
      - pyproject.toml
      - poetry.lock
    cmds:
      - poetry install

  test:
    sources:
      - ./**/*.py
    deps:
      - format
    cmds:
      - poetry run pytest --cov={{.PROJECT}} --cov-report=term --cov-report=html --verbose

  format:
    sources:
      - ./**/*.py
    cmds:
      - poetry run black .

  lint:
    sources:
      - ./**/*.py
    cmds:
      - poetry run black --check .
      - poetry run flake8 --show-source .

  dev:
    cmds:
      - poetry run uvicorn main:app --reload

  docs:
    dir: docs
    interactive: true
    cmds:
      - curl -sSL {{.SPEC_URL}} > openapi.json
      - poetry run python -m http.server {{.PORT}}
    vars:
      SPEC_URL: http://localhost:8000/openapi.json
      PORT: 8080
